# URL ??????????? ? ???? ?????? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# ??? ???????????? ??? PostgreSQL
spring.datasource.username=postgres

# ?????? ??? PostgreSQL
spring.datasource.password=mysecretpassword

# ??????? ??? PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ????????? ??? ?????? ? PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ????????? ??? ??????????????? ?????????? ????? ???? ??????
spring.jpa.hibernate.ddl-auto=update
